package org.druidanet.druidnetbeta.model

enum class UsageType {
    MEDICINAL, ALIMENTATION, ANIMAL_FOOD, VET, TOXIC, COMBUSTIBLE, CONSTRUCTION,
    INDUSTRY_CRAFT, ENVIRONMENTAL, ORNAMENTAL, SOCIAL
}

//enum class UsageType.MEDICINAL.SUBTYPES {
//    CIRCULATORIO
//}